import Layout from "../src/layout/Layout";
import PageBanner from "../src/layout/PageBanner";

const PrivacyPolicy = () => {
  return (
    <Layout pageName={"Privacy Policy"} isHome={false}>
      <PageBanner pageName="Privacy Policy" />
      
      <div className="container mx-auto px-6 py-12 max-w-4xl">
        <div className="bg-white/5 backdrop-blur-sm rounded-2xl p-8 text-white">
          
          <p className="text-gray-300 mb-6">Last updated: September 20, 2023</p>

          <div className="prose prose-invert max-w-none">
            <p className="mb-6">
              This Privacy Policy describes how Syntale Network (&quot;we&quot;, &quot;our&quot;, or &quot;us&quot;) collects, uses, and discloses your 
              Personal Data when you use our Service. It also outlines your data protection rights, including the right to 
              object to some of the processing we carry out.
            </p>

            <p className="mb-8">
              We use Your personal data to provide and improve our services. By using any Syntale services, You agree to the 
              collection and use of the information in accordance with this Privacy Policy.
            </p>

            <h2 className="text-2xl font-bold text-white mb-4 pb-2 border-b border-blue-500">
              Interpretation and Definitions
            </h2>

            <h3 className="text-xl font-semibold text-blue-400 mb-3">Interpretation</h3>
            <p className="mb-4">
              The words of which the initial letter is capitalized have meanings defined under the following conditions. 
              The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
            </p>

            <h3 className="text-xl font-semibold text-blue-400 mb-3">Definitions</h3>
            <p className="mb-4">For the purposes of this Privacy Policy:</p>

            <div className="space-y-3 mb-8">
              <p><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</p>
              
              <p><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</p>
              
              <p><strong>Application</strong> refers to Syntale, the software program provided by the Company.</p>
              
              <p><strong>Servers</strong> refer to the Unturned servers provided by the Company.</p>
              
              <p><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to Syntale Network, 123 N Sea RD, Southampton, NY 11969, PO Box 1530.</p>
              
              <p><strong>Cookies</strong> are small files that are placed on Your computer, mobile device, or any other device by a website, containing the details of Your browsing history on that website among its many uses.</p>
              
              <p><strong>Country</strong> refers to: New York, United States</p>
              
              <p><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone, or a digital tablet.</p>
              
              <p><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</p>
              
              <p><strong>Service</strong> refers to the Unturned Servers, Website, Discord server or all three.</p>
              
              <p><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</p>
              
              <p><strong>Third-party Social Media Service</strong> refers to any website or any social network website through which a User can log in or create an account to use the Service.</p>
              
              <p><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
              
              <p><strong>Website</strong> refers to Syntale, accessible from <a href="https://www.syntale.net/" className="text-blue-400 hover:text-blue-300">https://www.syntale.net/</a></p>
              
              <p><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>
            </div>

            <h2 className="text-2xl font-bold text-white mb-4 pb-2 border-b border-blue-500">
              Collecting and Using Your Personal Data
            </h2>

            <h3 className="text-xl font-semibold text-blue-400 mb-3">Types of Data Collected</h3>

            <h4 className="text-lg font-semibold text-blue-300 mb-2">Personal Data</h4>
            <p className="mb-4">
              While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
            </p>
            <ul className="list-disc list-inside mb-6">
              <li>Usage Data</li>
            </ul>

            <h4 className="text-lg font-semibold text-blue-300 mb-2">Usage Data</h4>
            <p className="mb-4">Usage Data is collected automatically when using the Service.</p>
            
            <p className="mb-4">
              Usage Data may include information such as Your Device&apos;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
            </p>

            <p className="mb-4">
              When You access Our Website by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
            </p>

            <p className="mb-4">
              We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.
            </p>

            <p className="mb-4">
              When you access Our Unturned Servers by or through a computer, tablet, mobile device, or any other electronic device with the capabilities of joining an Unturned server, We will collect your IP address, your unique steam id (Steam64 ID) and your unique HWID (Hardware Identification).
            </p>

            <div className="bg-blue-900/20 border-l-4 border-blue-400 p-4 mb-6">
              <p className="mb-2"><strong>Tebex-Discord Integration:</strong></p>
              <p>
                We utilize an integration between Tebex (Our store provider) and our Discord server to provide updates and notifications related to store transactions. As part of this integration, certain personal information might be transmitted to our Discord server via webhooks to private channels. This data might include usernames, transaction IDs, items purchased, email addresses, and IP addresses. This information is solely for the purpose of order fulfilment, customer support, and ensuring a seamless user experience. For more information on how Tebex handles personal information, please refer to their Privacy Policy.
              </p>
            </div>

            <h4 className="text-lg font-semibold text-blue-300 mb-2">Tracking Technologies and Cookies</h4>
            <p className="mb-4">
              We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.
            </p>

            <h3 className="text-xl font-semibold text-blue-400 mb-3">Use of Your Personal Data</h3>
            <p className="mb-4">The Company may use Personal Data for the following purposes:</p>
            
            <ul className="list-disc list-inside space-y-2 mb-6">
              <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
              <li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
              <li><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application&apos;s push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
              <li><strong>To provide You</strong> with news, special offers and general information about other goods, services and events which we offer that are similar to those that you may have already purchased or enquired about unless You have opted not to receive such information.</li>
              <li><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
              <li><strong>For business transfers:</strong> We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets.</li>
              <li><strong>For other purposes:</strong> We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</li>
            </ul>

            <h3 className="text-xl font-semibold text-blue-400 mb-3">Retention of Your Personal Data</h3>
            <p className="mb-4">
              The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.
            </p>

            <h3 className="text-xl font-semibold text-blue-400 mb-3">Security of Your Personal Data</h3>
            <p className="mb-6">
              The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
            </p>

            <h2 className="text-2xl font-bold text-white mb-4 pb-2 border-b border-blue-500">
              Children&apos;s Privacy
            </h2>
            <p className="mb-4">
              Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.
            </p>
            <p className="mb-6">
              If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent&apos;s consent before We collect and use that information.
            </p>

            <h2 className="text-2xl font-bold text-white mb-4 pb-2 border-b border-blue-500">
              Links to Other Websites
            </h2>
            <p className="mb-4">
              Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party&apos;s site. We strongly advise You to review the Privacy Policy of every site You visit.
            </p>
            <p className="mb-6">
              We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
            </p>

            <h2 className="text-2xl font-bold text-white mb-4 pb-2 border-b border-blue-500">
              Changes to this Privacy Policy
            </h2>
            <p className="mb-4">
              We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
            </p>
            <p className="mb-4">
              We will let You know via update the &quot;Last updated&quot; date at the top of this Privacy Policy.
            </p>
            <p className="mb-6">
              You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
            </p>

            <h2 className="text-2xl font-bold text-white mb-4 pb-2 border-b border-blue-500">
              Contact Us
            </h2>
            <p className="mb-4">If you have any questions about this Privacy Policy, You can contact us:</p>
            
            <div className="space-y-2">
              <p>By email: <a href="mailto:kevincantaloupe@gmail.com" className="text-blue-400 hover:text-blue-300">kevincantaloupe@gmail.com</a></p>
              <p>By mail: 123 N Sea RD, Southampton, NY 11969, PO Box 1530</p>
              <p>By Discord: <a href="https://discord.gg/syntale" className="text-blue-400 hover:text-blue-300" target="_blank" rel="noreferrer">https://discord.gg/syntale</a></p>
            </div>
          </div>
        </div>
      </div>
    </Layout>
  );
};

export default PrivacyPolicy; 